on: push

jobs:
  spellchecking:
    name: "spell checker for all md files"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

  repo-lint:
    name: "repolint"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0
      - name: Test repolinter
        uses: philips-labs/github-action-repolinter@master    
    # - uses: rojopolis/spellcheck-github-actions@0.24.0
    #   name: Spellcheck
    #   with:
    #     output_file: spellcheck-output.txt